//connectivity
export const INTERNET_CONNECTED = 'INTERNET_CONNECTED';
export const INTERNET_DISCONNECTED = 'INTERNET_DISCONNECTED';

//registration
export const REGISTRATION_LOADING = 'REGISTRATION_LOADING';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

//login
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Home Types
export const WATER_PROBLEM_PLACED = 'WATER_PROBLEM_PLACED';
export const WATER_PROBLEM_TYPE = 'WATER_PROBLEM_TYPE';
export const WATER_PROBLEM_NOTES = 'WATER_PROBLEM_NOTES';
export const WATER_PROBLEM_IMAGE = 'WATER_PROBLEM_IMAGE';
export const WATER_PROBLEM_LOCATION = 'WATER_PROBLEM_LOCATION';
export const WATER_PROBLEM_ADDRESS = 'WATER_PROBLEM_ADDRESS';
export const WATER_PROBLEM_DATE = 'WATER_PROBLEM_DATE';

export const CLEAR_PROBLEM_DATA = 'CLEAR_PROBLEM_DATA';
export const GET_QUICK_DATA_LOAD='GET_QUICK_DATA_LOAD'
export const GET_QUICK_FACT_SUCCESS='GET_QUICK_FACT_SUCCESS'
export const GET_QUICK_FACT_FAILED='GET_QUICK_FACT_FAILED'

// GET_QUICK_FACT_FAILED

// settings Types
export const GET_USER_PROFILE_LOADING = 'GET_USER_PROFILE_LOADING';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';

export const UPDATE_USER_PROFILE_LOADING = 'UPDATE_USER_PROFILE_LOADING';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILED = 'UPDATE_USER_PROFILE_FAILED';

export const EMAIL_US_LOADING = 'EMAIL_US_LOADING';
export const EMAIL_US_SUCCESS = 'EMAIL_US_SUCCESS';
export const EMAIL_US_FAILED = 'EMAIL_US_FAILED';

export const GET_REPORTS_LOADING = 'GET_REPORTS_LOADING';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const GET_REPORTS_FAILED = 'GET_REPORTS_FAILED';

export const SEND_REPORT_LOADING = 'SEND_REPORT_LOADING';
export const SEND_REPORT_SUCCESS = 'SEND_REPORT_SUCCESS';
export const SEND_REPORT_FAILED = 'SEND_REPORT_FAILED';
// NEWS
export const SEND_NEWS_LOADING = 'SEND_NEWS_LOADING';
export const SEND_NEWS_SUCCESS = 'SEND_NEWS_SUCCESS';
export const SEND_NEWS_FAILED = 'SEND_NEWS_FAILED';
export const GET_HEIGHT='GET_HEIGHT'

export const GET_STATIC_PAGES_LOADING = 'GET_STATIC_PAGES_LOADING';
export const GET_STATIC_PAGES_SUCCESS = 'GET_STATIC_PAGES_SUCCESS';
export const GET_STATIC_PAGES_FAILED = 'GET_STATIC_PAGES_FAILED';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// forgot password action types
export const FORGOT_PASSWORD_LOADING = 'FORGOT_PASSWORD_LOADING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

// change password action types
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

// Delete Account action types
export const DELETE_ACCOUNT_LOADING = 'DELETE_ACCOUNT_LOADING';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED';

//clear data
export const CLEAR_DATA = 'CLEAR_DATA';
export const UNAUTHORIZED = 'UNAUTHORIZED';

// news Data
export const GETNEWSDATA='GET_NEWS_DATA';
export const SET_REPORT_FOCUS="SET_REPORT_FOCUS";

// NOTIFICATION
export const GET_NOTICATION_SUCCESS="GET_NOTICATION_SUCCESS"
export const GET_NOTICATION_FAILED="GET_NOTICATION_FAILED"
export const GET_NOTICATION_DETAIL_SUCCESS="GET_NOTICATION_DETAIL_SUCCESS"
export const GET_NOTICATION_DETAIL_FAILED="GET_NOTICATION_DETAIL_FAILED"
export const OPEN_POPUP="OPEN_POPUP"
export const BROAD_CAST_NOTIFICATION_FLAG="BROAD_CAST_NOTIFICATION_FLAG"

